name = "edgetunnel-275"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./"

[[d1_databases]]
binding = "DB"
database_name = "edgetunnel-mvp"
database_id = "a72bb22e-ced5-4bb6-9a56-98ca5e8051ca"

[[kv_namespaces]]
binding = "KV"
id = "598410e3d73641398187ab18707712fa"
